version: 2.1
# Define the jobs we want to run for this project
jobs:
  deploy_functions:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: sudo npm install
      - run: 
          name: "Install Firebase"
          command: sudo npm install -g firebase-tools
      - run: 
          name: "Deploy Firebase Functions"
          command: npm run deploy

# Orchestrate our job run sequence
workflows:
  deploy:
    jobs:
      - deploy_functions
